
# from enum import Enum

# class CourseType(str, Enum):
#     LONG_TERM = "LONG_TERM"
#     SHORT_TERM = "SHORT_TERM" # Nếu là khóa học ngắn hạn thì khóa học chỉ có một môn học

# class CurriculumStatus(str, Enum):
#     CURRICULUM_DRAFT = "CURRICULUM_DRAFT"
#     CURRICULUM_PENDING = "CURRICULUM_PENDING"
#     CURRICULUM_ACTIVE = "CURRICULUM_ACTIVE"
#     CURRICULUM_ARCHIVED = "CURRICULUM_ARCHIVED"

# class SyllabusStatus(str, Enum):
#     SYLLABUS_DRAFT = "SYLLABUS_DRAFT"
#     SYLLABUS_REVIEWING = "SYLLABUS_REVIEWING"
#     SYLLABUS_APPROVED = "SYLLABUS_APPROVED"
#     SYLLABUS_REJECTED = "SYLLABUS_REJECTED"


# # class SubjectStatus(str, Enum):
# #     SUBJECT_DEVELOPING = "SUBJECT_DEVELOPING"
# #     SUBJECT_ACTIVE = "SUBJECT_ACTIVE"
# #     SUBJECT_SUSPENDED = "SUBJECT_SUSPENDED"


# class CourseStatus(str, Enum):
#     COURSE_REGISTRATION = "COURSE_REGISTRATION"
#     COURSE_UPCOMING = "COURSE_UPCOMING"
#     COURSE_ONGOING = "COURSE_ONGOING"
#     COURSE_COMPLETED = "COURSE_COMPLETED"


# class SubjectStatus(str, Enum):
#     DEVELOPING = "DEVELOPING" 
#     ACTIVE = "ACTIVE"          
#     SUSPENDED = "SUSPENDED"


from enum import Enum

class CourseType(str, Enum):
    LONG_TERM = "LONG_TERM"
    SHORT_TERM = "SHORT_TERM"

# 🟢 Curriculum trong Postgres lưu CÓ tiền tố "CURRICULUM_"
class CurriculumStatus(str, Enum):
    CURRICULUM_DRAFT = "CURRICULUM_DRAFT"
    CURRICULUM_PENDING = "CURRICULUM_PENDING"
    CURRICULUM_ACTIVE = "CURRICULUM_ACTIVE"
    CURRICULUM_ARCHIVED = "CURRICULUM_ARCHIVED"

# 🟢 Syllabus trong Postgres lưu KHÔNG CÓ tiền tố (Chỉ có "DRAFT")
class SyllabusStatus(str, Enum):
    SYLLABUS_DRAFT = "DRAFT"
    SYLLABUS_REVIEWING = "REVIEWING"
    SYLLABUS_APPROVED = "APPROVED"
    SYLLABUS_REJECTED = "REJECTED"

class CourseStatus(str, Enum):
    COURSE_REGISTRATION = "COURSE_REGISTRATION"
    COURSE_UPCOMING = "COURSE_UPCOMING"
    COURSE_ONGOING = "COURSE_ONGOING"
    COURSE_COMPLETED = "COURSE_COMPLETED"

class SubjectStatus(str, Enum):
    SUBJECT_DEVELOPING = "SUBJECT_DEVELOPING"
    SUBJECT_ACTIVE = "SUBJECT_ACTIVE"
    SUBJECT_SUSPENDED = "SUBJECT_SUSPENDED"
