apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DB_HOST: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: YWJjMTIz
  SECRET_KEY: MjRiMGE4YzdhZDkyNWEzZTI0ZTk5Y2UzNmIzYzUzYjJiMzNiNTQyMDk4NjExY2IxNGZjMDIzNzBjNDRkYTM5MA==